[package]
name = "wannsea_types"
version = "0.1.101"
edition = "2021"
build = "src/build.rs"

[dependencies]
pbjson = "0.6.0"
pbjson-types = "0.6.0"
prost = "*"
serde = "1.0.195"

[build-dependencies]
prost-build = { version = "*" }
pbjson-build = "0.6.0"
