[build-system]
requires = [ "setuptools",]
build-backend = "setuptools.build_meta"

[project]
name = "wannsea_types"
version = "0.0.14"
description = ""
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
packages = [ "types",]
