[build-system]
requires = [ "setuptools",]
build-backend = "setuptools.build_meta"

[project]
name = "wannsea-lib"
version = "0.0.12"
description = ""
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
packages = [ "types",]
