name: WannSea Shore Core v2 trigger 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rebuild:
    uses: WannSea/shore-core-v2/.github/workflows/server.yml@main
    
